const express= require('express')
const router = express.Router()
const authRouter = require('./auth')
const userRouter = require('./user')
const bookRouter = require('./book')
const movieRouter = require('./movie')
const gameRouter = require('./game')
const bookCategoryRouter = require('./book-category')
const movieCategoryRouter = require('./movie-category')
const gameCategoryRouter = require('./game-category')

router.use('/auth', authRouter)
router.use('/user', userRouter)
router.use('/book', bookRouter)
router.use('/movie', movieRouter)
router.use('/game', gameRouter)
router.use('/bookCategory', bookCategoryRouter)
router.use('/movieCategory', movieCategoryRouter)
router.use('/gameCategory', gameCategoryRouter)

module.exports = router